# Generated by Django 2.2 on 2021-08-27 09:00

from django.db import migrations, models
import django.db.models.deletion
import struttureGioco.models
import struttureGioco.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('luogo', models.CharField(max_length=100, null=True, unique=True)),
                ('vita', models.IntegerField(default=10)),
                ('abilitato', models.BooleanField(default=False)),
                ('vitalita', models.IntegerField(default=0)),
                ('forza', models.IntegerField(default=0)),
                ('destrezza', models.IntegerField(default=0)),
                ('intelligenza', models.IntegerField(default=0)),
                ('tempra', models.IntegerField(default=0)),
                ('image', models.ImageField(null=True, storage=struttureGioco.storage.OverwriteStorage(), upload_to=struttureGioco.models.Boss.upload_location)),
            ],
        ),
        migrations.CreateModel(
            name='Equipaggiamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('tipo', models.CharField(choices=[('P', 'ArmaPrimaria'), ('S', 'ArmaSecondaria'), ('A', 'Armatura')], max_length=1, null=True)),
                ('abilitato', models.BooleanField(default=True)),
                ('vitalita', models.IntegerField(default=0)),
                ('forza', models.IntegerField(default=0)),
                ('destrezza', models.IntegerField(default=0)),
                ('intelligenza', models.IntegerField(default=0)),
                ('tempra', models.IntegerField(default=0)),
                ('boss', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='struttureGioco.Boss')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipaggiamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='struttureGioco.Equipaggiamento')),
            ],
        ),
        migrations.CreateModel(
            name='Personaggio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, null=True)),
                ('vita', models.IntegerField(default=10)),
                ('vitalita', models.IntegerField(default=1)),
                ('forza', models.IntegerField(default=2)),
                ('destrezza', models.IntegerField(default=1)),
                ('intelligenza', models.IntegerField(default=1)),
                ('tempra', models.IntegerField(default=1)),
                ('armaPrimaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='struttureGioco.Equipaggiamento')),
                ('armaSecondaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='struttureGioco.Equipaggiamento')),
                ('armatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='struttureGioco.Equipaggiamento')),
                ('zaino', models.ManyToManyField(through='struttureGioco.Inventario', to='struttureGioco.Equipaggiamento')),
            ],
        ),
        migrations.AddField(
            model_name='inventario',
            name='personaggio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='struttureGioco.Personaggio'),
        ),
        migrations.AlterUniqueTogether(
            name='inventario',
            unique_together={('personaggio', 'equipaggiamento')},
        ),
    ]
