# Generated by Django 2.2 on 2021-08-07 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('luogo', models.CharField(max_length=100, null=True)),
                ('vita', models.IntegerField(default=10)),
                ('abilitato', models.BooleanField(default=False)),
                ('vitalita', models.IntegerField(default=0)),
                ('forza', models.IntegerField(default=0)),
                ('destrezza', models.IntegerField(default=0)),
                ('intelligenza', models.IntegerField(default=0)),
                ('tempra', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Equipaggiamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('tipo', models.CharField(choices=[('P', 'ArmaPrimaria'), ('S', 'ArmaSecondaria'), ('A', 'Armatura')], max_length=1, null=True)),
                ('abilitato', models.BooleanField(default=True)),
                ('vitalita', models.IntegerField(default=0)),
                ('forza', models.IntegerField(default=0)),
                ('destrezza', models.IntegerField(default=0)),
                ('intelligenza', models.IntegerField(default=0)),
                ('tempra', models.IntegerField(default=0)),
                ('boss', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='struttureGioco.Boss')),
            ],
        ),
    ]
