# Generated by Django 2.2 on 2021-08-07 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('struttureGioco', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personaggio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vita', models.IntegerField(default=10)),
                ('vitalita', models.IntegerField(default=0)),
                ('forza', models.IntegerField(default=0)),
                ('destrezza', models.IntegerField(default=0)),
                ('intelligenza', models.IntegerField(default=0)),
                ('tempra', models.IntegerField(default=0)),
                ('armaPrimaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='struttureGioco.Equipaggiamento')),
                ('armaSecondaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='struttureGioco.Equipaggiamento')),
                ('armatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='struttureGioco.Equipaggiamento')),
            ],
        ),
    ]
