# Generated by Django 2.2 on 2021-08-07 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('struttureGioco', '0003_inventario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='equipaggiamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='struttureGioco.Equipaggiamento', unique=True),
        ),
    ]
