# Generated by Django 2.2 on 2021-08-07 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('struttureGioco', '0004_auto_20210807_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='equipaggiamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='struttureGioco.Equipaggiamento'),
        ),
        migrations.AlterUniqueTogether(
            name='inventario',
            unique_together={('personaggio', 'equipaggiamento')},
        ),
    ]
