# Generated by Django 2.2 on 2021-08-09 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('struttureGioco', '0005_auto_20210807_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaggio',
            name='zaino',
            field=models.ManyToManyField(through='struttureGioco.Inventario', to='struttureGioco.Equipaggiamento'),
        ),
    ]
