# Generated by Django 2.2 on 2021-08-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('struttureGioco', '0006_personaggio_zaino'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaggio',
            name='nome',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
