# Generated by Django 2.2 on 2021-08-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('struttureGioco', '0009_auto_20210809_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaggio',
            name='nome',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
