# Generated by Django 2.2 on 2021-08-09 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('struttureGioco', '0010_auto_20210809_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipaggiamento',
            name='boss',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='struttureGioco.Boss'),
        ),
        migrations.AlterField(
            model_name='personaggio',
            name='nome',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
