# Generated by Django 2.2 on 2021-08-09 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('struttureGioco', '0012_auto_20210809_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipaggiamento',
            name='boss',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='struttureGioco.Boss'),
        ),
    ]
