# Generated by Django 2.2 on 2021-08-09 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('struttureGioco', '0013_auto_20210809_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaggio',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='personaggio',
            name='zaino',
        ),
    ]
