# Generated by Django 2.2 on 2021-08-09 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('struttureGioco', '0014_auto_20210809_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaggio',
            name='nome',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='personaggio',
            name='zaino',
            field=models.ManyToManyField(through='struttureGioco.Inventario', to='struttureGioco.Equipaggiamento'),
        ),
    ]
