# Generated by Django 3.2.6 on 2021-08-20 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('struttureGioco', '0015_auto_20210809_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boss',
            name='luogo',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
