# Generated by Django 2.2 on 2021-08-18 15:01

from django.db import migrations, models
import struttureGioco.models


class Migration(migrations.Migration):

    dependencies = [
        ('struttureGioco', '0015_auto_20210809_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='boss',
            name='image',
            field=models.ImageField(null=True, upload_to=struttureGioco.models.Boss.upload_location),
        ),
        migrations.AlterField(
            model_name='boss',
            name='luogo',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
