# Generated by Django 2.2 on 2021-08-18 15:17

from django.db import migrations, models
import struttureGioco.models


class Migration(migrations.Migration):

    dependencies = [
        ('struttureGioco', '0016_auto_20210818_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boss',
            name='image',
            field=models.ImageField(null=True, storage=struttureGioco.models.OverwriteStorage(location='../progISW/home/static/imgB/'), upload_to=struttureGioco.models.Boss.upload_location),
        ),
    ]
