# Generated by Django 2.2 on 2021-08-18 15:23

from django.db import migrations, models
import struttureGioco.models
import struttureGioco.storage


class Migration(migrations.Migration):

    dependencies = [
        ('struttureGioco', '0017_auto_20210818_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boss',
            name='image',
            field=models.ImageField(null=True, storage=struttureGioco.storage.OverwriteStorage(), upload_to=struttureGioco.models.Boss.upload_location),
        ),
    ]
