# Generated by Django 2.2 on 2021-08-07 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('struttureGioco', '0002_personaggio'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='personaggio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='struttureGioco.Personaggio'),
        ),
    ]
